const BACKGROUND = '#151515';
const BACKGROUND_BORDER = '#242424';
const BACKGROUND_DARK = '#0F0F0F';
const BACKGROUND_DARKER = '#151515';
const BACKGROUND_LIGHT = '#4F4F4F';
const PRIMARY = '#B74343';
const PRIMARY_DARK = '#8A3232';
const PRIMARY_LIGHT = '#CD7575';
const SECONDARY = '#69CD9D';
const SECONDARY_LIGHT = '#F2E5A4';
const SECONDARY_DARK = '#E9D261';
const TERTIARY = '#4A648D';
const TEXT_PRIMARY = '#F9DCC5';
const TEXT_SECONDARY = '#E1DFDB';
const TEXT_BODY = '#F4F0F0';
const TEXT_WHITE = '#FFFFFF';
const TEXT_GRAY = '#C7C7C7';
const TEXT_PLACEHOLDER = '#4D4A41';
const NEUTRAL_GREY = '#C7C7C7';
const SPOTIFY_GREEN = '#1DB954';
const white = '#FFFFFF';
const white_o_72 = 'rgba(255,255,255,0.72)';

const colors = {
  BACKGROUND,
  BACKGROUND_BORDER,
  BACKGROUND_DARK,
  BACKGROUND_DARKER,
  BACKGROUND_LIGHT,
  PRIMARY,
  PRIMARY_DARK,
  PRIMARY_LIGHT,
  SECONDARY,
  SECONDARY_DARK,
  SECONDARY_LIGHT,
  TERTIARY,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  TEXT_PLACEHOLDER,
  TEXT_BODY,
  TEXT_WHITE,
  TEXT_GRAY,
  NEUTRAL_GREY,
  SPOTIFY_GREEN,
  white,
  white_o_72,
} as const;

export default colors;
